### ISSUE TITLE
Cannot do mutation with certain reside

### ISSUE THREAD

**Issue by xiki-tempula** [deGrootLab/pmx#13]
I'm trying to mutate FAQ to AAA.
The gro file for FAQ is
```
MDANALYSIS FRAME 0: Created by PDBWriter
   50
    1PHE      N    1   5.894   7.535   8.466
    1PHE     H1    2   5.925   7.620   8.511
    1PHE     H2    3   5.869   7.549   8.369
    1PHE     H3    4   5.806   7.502   8.504
    1PHE     CA    5   5.998   7.433   8.483
    1PHE     HA    6   5.950   7.338   8.458
    1PHE     CB    7   6.127   7.451   8.403
    1PHE    HB1    8   6.195   7.368   8.423
    1PHE    HB2    9   6.161   7.552   8.429
    1PHE     CG   10   6.122   7.460   8.252
    1PHE    CD1   11   6.017   7.409   8.180
    1PHE    HD1   12   5.930   7.365   8.227
    1PHE    CE1   13   6.003   7.449   8.049
    1PHE    HE1   14   5.919   7.410   7.993
    1PHE     CZ   15   6.099   7.525   7.982
    1PHE     HZ   16   6.089   7.555   7.879
    1PHE    CE2   17   6.210   7.566   8.057
    1PHE    HE2   18   6.281   7.628   8.005
    1PHE    CD2   19   6.219   7.539   8.193
    1PHE    HD2   20   6.306   7.574   8.247
    1PHE      C   21   6.026   7.423   8.635
    1PHE      O   22   6.073   7.525   8.691
    2ALA      N   23   6.020   7.305   8.698
    2ALA      H   24   6.001   7.221   8.645
    2ALA     CA   25   6.063   7.285   8.837
    2ALA     HA   26   6.026   7.358   8.908
    2ALA     CB   27   6.004   7.153   8.880
    2ALA    HB1   28   6.049   7.064   8.837
    2ALA    HB2   29   6.020   7.152   8.988
    2ALA    HB3   30   5.896   7.151   8.868
    2ALA      C   31   6.214   7.293   8.855
    2ALA      O   32   6.261   7.334   8.961
    3GLN      N   33   6.292   7.255   8.754
    3GLN      H   34   6.241   7.201   8.685
    3GLN     CA   35   6.431   7.272   8.745
    3GLN     HA   36   6.467   7.353   8.808
    3GLN     CB   37   6.503   7.147   8.800
    3GLN    HB1   38   6.588   7.112   8.742
    3GLN    HB2   39   6.445   7.055   8.796
    3GLN     CG   40   6.541   7.165   8.949
    3GLN    HG1   41   6.585   7.075   8.990
    3GLN    HG2   42   6.449   7.174   9.007
    3GLN     CD   43   6.635   7.275   8.992
    3GLN    OE1   44   6.755   7.281   8.952
    3GLN    NE2   45   6.591   7.359   9.080
    3GLN   HE21   46   6.492   7.353   9.097
    3GLN   HE22   47   6.641   7.435   9.123
    3GLN      C   48   6.485   7.312   8.604
    3GLN    OC1   49   6.541   7.420   8.586
    3GLN    OC2   50   6.477   7.228   8.512
  12.28070  12.28070  13.81770
```
However, I got 
pmx mutate -f FAQ_ligand.gro -o FAQ_ligand.mutant.gro
Choose a force field:

  [i]    name                                    description
  ---    ----                                    -----------
  [1]    amber14sbmut                            MUT_Amber_ff14sb (ported by Man Hoang Viet, North Carolina State University)
  [2]    amber99sb-star-ildn-bsc1-mut            [Protein, DNA] Amber99sb-star-ildn-bsc1 for DNA (Best & Hummer 2009, Lindorff-Larsen et al. 2010)
  [3]    amber99sb-star-ildn-dna-mut             [Protein, DNA] Amber99sb-star-ildn (Best & Hummer 2009, Lindorff-Larsen et al. 2010)
  [4]    amber99sb-star-ildn-mut                 [Protein] Amber99sb-star-ildn (Best & Hummer 2009, Lindorff-Larsen et al. 2010)
  [5]    charmm22star-mut                        CHARMM22* all-atom force field
  [6]    charmm36m-mut                           [Protein, DNA] Charmm36m all-atom force field (November 2016)

Enter the index [i] of the chosen forcefield: 1

Select residue to mutate:
     1-PHE-      2-ALA-      3-GLN- 
Enter residue number: 1

Select new amino acid for 1-PHE: 
Three- or one-letter code (or four-letter for ff specific residues): ALA
Will apply mutation F->A on residue PHE-1
log_> Residue to mutate: 1 | PHE |   
log_> Mutation to apply: F->A
log_> Hybrid residue name: F2A
Traceback (most recent call last):
  File "/Users/XXX/opt/miniconda3/envs/pmx/bin/pmx", line 10, in <module>
    sys.exit(entry_point())
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/scripts/cli.py", line 86, in entry_point
    PmxCli()
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/scripts/cli.py", line 41, in __init__
    getattr(self, args.command)()
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/scripts/cli.py", line 45, in mutate
    mutate.entry_point()
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/scripts/mutate.py", line 578, in entry_point
    main(args)
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/scripts/mutate.py", line 564, in main
    verbose=True)
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/alchemy.py", line 82, in mutate
    mtp_file=mtp_file, refB=refB, verbose=verbose)
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/alchemy.py", line 116, in apply_aa_mutation
    bb_super(residue, hybrid_res)
  File "/Users/XXX/opt/miniconda3/envs/pmx/lib/python3.7/site-packages/pmx/geometry.py", line 135, in bb_super
    assert len(atoms1) == len(atoms2), "%s -> %s" % ('-'.join(map(lambda a: a.name, atoms1)), '-'.join(map(lambda a: a.name, atoms2)))
AssertionError: N-CA-C-O-HA -> N-CA-C-H-O-HA

**Comment by vgapsys** [comment]
Mutations of terminal residues are not supported. To mutate the first (or last) residue, you would need to add a capping group, this way making the residue non-terminal.

**Comment by xiki-tempula** [comment]
Thank you for your reply. I'm working on the binding of tri-peptide so I guess capping won't work
