### ISSUE TITLE
Error with Zn atom

### ISSUE THREAD

**Issue by almeida85** [deGrootLab/pmx#23]
Hello,

I am trying to prepare a DSSB system with `pmx doublebox`, but I get an error with a Zn atom. I have tried saving the pdb in several ways but still get this error:

```
Traceback (most recent call last):
  File "/home/almeida/.local/bin/pmx", line 8, in <module>
    sys.exit(entry_point())
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/scripts/cli.py", line 97, in entry_point
    PmxCli()
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/scripts/cli.py", line 44, in __init__
    getattr(self, args.command)()
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/scripts/cli.py", line 68, in doublebox
    make_double_box.entry_point()
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/scripts/make_double_box.py", line 72, in entry_point
    main(args)
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/scripts/make_double_box.py", line 65, in main
    mout = double_box(m1=m1, m2=m2, r=args.r, d=args.d,
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/model.py", line 1165, in double_box
    com1, rad1 = _get_com_radius(m1)
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/model.py", line 1087, in _get_com_radius
    amass = _get_mass(a)
  File "/home/almeida/.local/lib/python3.8/site-packages/pmx/model.py", line 1036, in _get_mass
    return(library._atommass[aname[0]])
KeyError: 'Z'
```

Any help will be appreciated.
Best

**Comment by vgapsys** [comment]
Fixed in the commit 203ce7127304ba0793dfa75484c2aca96f7e33a0
