### ISSUE TITLE
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by JiangXu123** [deGrootLab/pmx#39]
python setup.py install
/usr/local/pmx/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/usr/local/pmx/setup.py", line 43, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pmx/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/usr/local/pmx/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pmx/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

**Comment by JiangXu123** [comment]
I am trying to install pmx on my Mac(BigSur Ver 11.6.5), I created a conda environment with package version listed below:
# packages in environment at /Users/jiangxu/anaconda3/envs/pmx:
#
# Name                    Version                   Build  Channel
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py312hbf0bb39_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
fonttools                 4.44.0          py312h41838bb_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
kiwisolver                1.4.5           py312h49ebfd2_1    conda-forge
lcms2                     2.15                 hd6ba6f3_3    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           19_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           19_osx64_openblas    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.19                 ha4e1b8e_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_1    conda-forge
libgfortran5              13.2.0               h2873a65_1    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
liblapack                 3.9.0           19_osx64_openblas    conda-forge
libopenblas               0.3.24          openmp_h48a4ad5_0    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libsqlite                 3.44.0               h92b6c6a_0    conda-forge
libtiff                   4.6.0                h684deea_2    conda-forge
libwebp-base              1.3.2                h0dc2134_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               17.0.4               hb6ac08f_0    conda-forge
matplotlib                3.8.1           py312hb401068_0    conda-forge
matplotlib-base           3.8.1           py312h1fe5000_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h93d8f39_2    conda-forge
numpy                     1.26.0          py312h5df92dc_0    conda-forge
openjpeg                  2.5.0                ha4da562_3    conda-forge
openssl                   3.1.4                hd75f5a5_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pillow                    10.1.0          py312h0c70c2f_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
python                    3.12.0          h30d4d87_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
scipy                     1.11.3          py312h2c2f0bb_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tornado                   6.3.3           py312h104f124_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge

**Comment by JiangXu123** [comment]
And then I tried to install the pmx of the development branch to be compatible with python 3 as shown below:
sudo git checkout develop
python setup.py install 

And I saw the error message shown above, So how can I solve this problem?

**Comment by vgapsys** [comment]
It seems like a versioneer issue: likely it doesn't work with the latest python. Need to fix this in the future, but for now you could try using an older python version
