### ISSUE TITLE
scipy.integrate.simps is an expired deprecation

### ISSUE THREAD

**Issue by michael-robo** [deGrootLab/pmx#51]
Hello pmx development team,

If I create a new pmx environment
```
conda create -n pmx
conda activate pmx
conda install -c conda-forge python=3.11 setuptools numpy scipy matplotlib rdkit
```
and then install the development branch of pmx
```
git clone https://github.com/deGrootLab/pmx pmx
cd pmx
git checkout develop
python setup.py install
```
pmx installs as normal. However, when I try to use pmx, I get the following error:
```
(pmx) [mrobo@IBRILPT72:~/Programs/pmx] pmx -h
Traceback (most recent call last):
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/bin/pmx", line 33, in <module>
    sys.exit(load_entry_point('pmx==0+untagged.879.gb0b5684', 'console_scripts', 'pmx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/bin/pmx", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/lib/python3.11/site-packages/pmx-0+untagged.879.gb0b5684-py3.11-linux-x86_64.egg/pmx/__init__.py", line 46, in <module>
    from .analysis import *
  File "/home/mrobo/anaconda3/envs/pmx_DEBUG/lib/python3.11/site-packages/pmx-0+untagged.879.gb0b5684-py3.11-linux-x86_64.egg/pmx/analysis.py", line 6, in <module>
    from scipy.integrate import simps
ImportError: cannot import name 'simps' from 'scipy.integrate' (/home/mrobo/anaconda3/envs/pmx_DEBUG/lib/python3.11/site-packages/scipy/integrate/__init__.py)
```
I've attached the output of "conda list" for a working environment and this failed environment below: 
[working_pmx_example.txt](https://github.com/user-attachments/files/17876715/working_pmx_example.txt)
[example_failure.txt](https://github.com/user-attachments/files/17876722/example_failure.txt)

Notably, in my working environment, I use scipy=1.11 , but in this failed environment, I use scipy=1.14

This can be traced to a change made in scipy version 1.14 that expires the deprecated scipy.integrate.simps feature (see https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations)

Downgrading scipy from 1.14 to 1.13 fixes the issue:
```
(pmx) [mrobo@IBRILPT72:~/Programs/pmx] conda install -c conda-forge scipy=1.13
... A lot of text output from conda ...
(pmx) [mrobo@IBRILPT72:~/Programs/pmx] pmx -h
usage: pmx [-h] [-v]

    ------------------------
    pmx command line scripts
    ------------------------

    Available commands are:
        mutate        Mutate protein or DNA/RNA
        gentop        Fill hybrid topology with B states
        analyse       Estimate free energy from Gromacs xvg files

        atomMapping   Ligand alchemy: map atoms for morphing
        ligandHybrid  Ligand alchemy: hybrid structure/topology

        doublebox     Place two input structures into a single box
        abfe          Setup files for an ABFE calculation

        genlib        Generate pmx ff library
        gmxlib        Show/set GMXLIB path

options:
  -h, --help     show this help message and exit
  -v, --version  show program's version number and exit
```

It appears that pmx no longer functions with the latest version of scipy.

Thank you for your support,
Michael Robo
Computational Chemistry Staff Scientist
Indiana Biosciences Research Institute

**Comment by vgapsys** [comment]
Are you sure you pulled the latest pmx version? This commit addressed the problem: https://github.com/deGrootLab/pmx/commit/e6d62580df7374c24e3056db5142517b8475daba

**Comment by michael-robo** [comment]
Thanks Vytautas. I tried again using the most recent version of pmx and it functioned as normal.
